Repository snippet-labs/COMPONENTLAB, pull requests merged in 2025-09, with the labels that each got.

#8 [CLIENT] [TESTS] Added Unit Tests for the Content.tsx component
  .github/workflows/Integration.yml
  bun.lock
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Ui/Content/Content.test.tsx
  src/components/Ui/Content/Content.tsx
  src/components/Ui/Content/Content.types.ts
  src/components/Ui/Navigation/Navigation.tsx
  src/components/Ui/Navigation/Navigation.types.ts
  src/components/Ui/ProgessPanel/ProgressPanel.test.tsx
  src/components/Ui/ProgessPanel/ProgressPanel.tsx
  src/components/Ui/ProgessPanel/ProgressPanel.types.ts
  src/components/Ui/Sidebar/Sidebar.tsx
  src/components/Ui/Sidebar/Sidebar.types.ts
  src/components/Wrapper/Wrapper.test.tsx
  src/components/Wrapper/Wrapper.tsx
  src/components/Wrapper/Wrapper.types.ts
  src/constants/NavigationItems.ts
  src/constants/ProgessItems.ts
  src/constants/SidebarItems.ts
  src/hooks/useScrollSpy.ts
  src/hooks/useSidebarSearch.ts
  src/types.ts
  tsconfig.json
Labels: component, test

#11 [CLIENT] [COMPONENT] Integrated Header Component
  bun.lock
  package.json
  src/app/page.test.tsx
  src/app/page.tsx
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Ui/Content/Content.tsx
  src/components/Ui/ProgessPanel/ProgressPanel.test.tsx
Labels: component, feature

#17 [CLIENT] [FEATURE]: Reusable Pagination
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Ui/Content/Content.tsx
  src/components/Ui/Pagination/Pagination.test.tsx
  src/components/Ui/Pagination/Pagination.tsx
  src/components/Ui/Pagination/Pagination.types.tsx
  src/constants/QuickLinkItems.ts
  src/types.ts
Labels: component, update, page

#29 [CLIENT] [IMPROVEMENT] [TEST] [COVERAGE] Navigation bar github link
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/tests/not-found.test.tsx
  src/app/tests/page.test.tsx
  src/components/Pages/Header/Header.test.tsx
  src/components/Pages/Header/Header.tsx
  src/components/Ui/Content/Content.test.tsx
  src/components/Ui/Navigation/Navigation.test.tsx
  src/components/Ui/Navigation/Navigation.tsx
  src/components/Ui/Navigation/Navigation.types.ts
  src/components/Ui/Pagination/Pagination.test.tsx
  src/components/Ui/ProgressPanel/ProgressPanel.test.tsx
  src/components/Ui/ProgressPanel/ProgressPanel.tsx
  src/components/Ui/ProgressPanel/ProgressPanel.types.ts
  src/components/Ui/Sidebar/Sidebar.test.tsx
  src/components/Wrapper/Wrapper.test.tsx
  src/components/Wrapper/Wrapper.tsx
  src/constants/Header/QuickLinkItems.ts
  src/constants/NavigationItems.ts
  src/constants/ProgressItems.ts
  src/helpers/font.ts
  src/hooks/tests/useScrollSpy.test.ts
  src/hooks/tests/useSidebarSearch.test.ts
  src/tests/setup.ts
  vitest.config.ts
Labels: optimization, enhancement, component, test

#35 [CLIENT] [COMPONENT] Dynamic footer
  src/app/not-found.tsx
  src/components/Pages/Header/Header.tsx
  src/components/Ui/Footer/Footer.test.tsx
  src/components/Ui/Footer/Footer.tsx
  src/components/Ui/Pagination/Pagination.tsx
  src/constants/Footer/FooterLinks.ts
  src/tests/setup.ts
Labels: component, feature

#38 [CLIENT] [FEATURE] Infinite text gradient animation
  src/app/globals.css
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/Pages/Header/Header.tsx
  src/components/Ui/Footer/Footer.tsx
  src/helpers/font.ts
Labels: bugfix, enhancement, component, feature

#43 [CLIENT] [BUGFIX] Side Panel scrolling mechanism
  src/components/Ui/Sidebar/Sidebar.tsx
Labels: bugfix, component

#44 [CLIENT] [TEST] SidePanel Installation Guide Page
  src/app/installation/page.test.tsx
  src/components/Ui/Pagination/Pagination.tsx
  src/components/Ui/Sidebar/Sidebar.tsx
Labels: test, page

#45 [CLIENT] [PAGE] [SIDEPANEL] Accessible Starter Layout Component
  src/app/button/ButtonVariants.ts
  src/app/button/page.tsx
  src/app/installation/page.tsx
  src/components/Ui/Pagination/Pagination.tsx
  src/components/Ui/Sidebar/Sidebar.tsx
  src/components/Ui/Starter/Starter.tsx
  src/components/Ui/Starter/Starter.types.ts
  src/constants/SidebarItems.ts
  src/hooks/tests/useSidebarSearch.test.ts
  src/types.ts
Labels: component, feature
